### ISSUE TITLE
Mobile scroll issue

### ISSUE THREAD

**Issue by jeffreykthomas** [Alexeykhr/vue-stripe-menu#227]
Hello, I am having trouble being able to add any css that will allow the vsm-mob-content to scroll (when the amount fills the height of the screen). Do you have any suggestions?

**Comment by Alexeykhr** [comment]
Hello, sorry for the late reply. It's certainly bad with styles, but I'll try to help somehow:

1. First option through normal styles and **vh** usage, [but that's bad](https://bokand.github.io/demo/urlbarsize.html)

You can try to solve the problem through js, [like this](https://css-tricks.com/the-trick-to-viewport-units-on-mobile/) or others.

```scss
.vsm-mob-content__wrap {
  height: calc(100vh - #{$vsm-mob-dropdown-offset} * 2);
  > .YOUR_INNER_CLASS {
    overflow-y: auto;
    overflow-x: hidden;
    height: 100%;
  }
}
```

If the close button should not scroll, then all styles can be added only in `.vsm-mob-content__wrap` class.

You can try to solve the problem through js, [like this](https://css-tricks.com/the-trick-to-viewport-units-on-mobile/) or others.

2. There is also a dirty hack, such as take the `.vsm-mob-content__wrap` element and move it to the end of the` </body> `, and there is already a huge scope for customization without any problems.

But I don't even know if it's worth doing, it's probably better to fork and replace the implementation inside the component.
