### ISSUE TITLE
Dropdown arrow 

### ISSUE THREAD

**Issue by modys** [Alexeykhr/vue-stripe-menu#239]
Hello everybody!

Anyone knows how to use the "drop down arrow" in vue stripe menu? I checked up this small guide of variable list. [link](https://github.com/Alexeykhr/vue-stripe-menu/blob/master/src/scss/_variables.scss)
but still does not work. May somebody can help and know more than me. Would be thankful!

**Comment by Alexeykhr** [comment]
Hi, I don't understand the question. You mean:

- How to change (or replace the styles) in the dropdown arrow?
- How to use dropdown arrow in other components?
- Or is the dropdown arrow not displayed on the site?

**Comment by modys** [comment]
Hi, thank you for fast respond. Yes i need to show the arrow for the dropdown navigation.  Like this one,
<img width="308" alt="Снимок экрана 2022-01-23 в 21 47 05" src="https://user-images.githubusercontent.com/16868206/150697435-f643aae4-4d50-4157-a0e0-3f9cfb369cce.png">
But not found how to do that. If you can help would be tahnkful!

**Comment by Alexeykhr** [comment]
You can try through the `title` slot:

```vue
<vsm-menu>
    <template #title="{ item }">
      <div>
        {{ item.title }}
        <span class="dropdown-arrow">\/<!--svg--></span>
      </div>
    </template>
</vsm-menu />
```

And rotate with css, like:

```css.dropdown-arrow {
    transition: transform .2s;
}
.vsm-has-dropdown:hover .dropdown-arrow {
    transform: rotate(
90deg);
    display: inline-block;
}
```
